build:
  check:
    image: framgia/laravel-workspace:latest
    commands:
      - cp .env.example .env
      - composer install
      - php artisan key:generate
      - npm install
      - npm run dev # or gulp
      - framgia-ci run
    when:
      event: push
compose:
  database:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: laravel57
      MYSQL_USER: user
      MYSQL_PASSWORD: s3cret
      MYSQL_ROOT_PASSWORD: root
cache:
  mount:
    - node_modules
    - vendor
    - .git
notify:
  chatwork:
    image: fdplugins/chatwork
    room_id: $$CHATWORK_ROOM_ID
    token: $$CHATWORK_TOKEN
    format: "TO ALL >>>\r\n[info][title]{repo.owner}/{repo.name}#{build.commit} {build.status}[/title]Branch: {build.branch}\r\nAuthor: {build.author}\r\nMessage: {build.message}\r\nhttp://ci-reports.framgia.vn/repositories/{repo.full_name}/builds/{build.number}/violations/[/info]"
    when:
      event: [push]
      branch: dev/develop*
