build:
  check:
    image: framgia/laravel-workspace:latest
    commands:
      - npm install
      - framgia-ci run
cache:
  mount:
    - node_modules
    - vendor
    - .git
notify:
  chatwork:
    image: fdplugins/chatwork
    room_id: $$CHATWORK_ROOM_ID
    token: $$CHATWORK_TOKEN
    format: "TO ALL >>>\r\n[info][title]{repo.owner}/{repo.name}#{build.commit} {build.status}[/title]Branch: {build.branch}\r\nAuthor: {build.author}\r\nMessage: {build.message}\r\nhttp://ci-reports.framgia.vn/repositories/{repo.full_name}/builds/{build.number}/violations/[/info]"
    when:
      event: [push]
      branch: dev/develop*
